### ISSUE TITLE
'solve' occasionally and non-deterministically gives wrong solution

### ISSUE THREAD

**Issue by feuerbach** [amosr/limp-cbc#5]
I wrote a QuickCheck test to demonstrate this:

``` haskell
{-# LANGUAGE FlexibleInstances, ScopedTypeVariables, TupleSections #-}
{-# OPTIONS_GHC -fno-warn-orphans #-}
import Test.Tasty
import Test.Tasty.QuickCheck
import Test.QuickCheck.Property
import Data.IORef
import Data.Void
import Data.Either
import Numeric.Limp.Solvers.Cbc (solve, Error(..))
import Numeric.Limp.Program
import Numeric.Limp.Rep.IntDouble

main :: IO ()
main = defaultMain limpTest

instance Arbitrary (Program Int Void IntDouble) where
  arbitrary = do
    let
      vars :: [Int]
      vars = [1 .. 10]
      bounds = map binary vars
      obj = LZ ((,1) <$> vars) 0
    constraints <- fmap mconcat . vectorOf 5 $ do
      vars1 <- sublistOf vars
      return $ LZ ((,1) <$> vars1) 0 :== c1
    return $ minimise obj constraints bounds
  
instance Eq Error where
  Infeasible == Infeasible = True

limpTest :: TestTree
limpTest = testProperty "limp" $ \(prog1 :: Program Int Void IntDouble) ->
  ioProperty $ do
    -- prevent CSE
    v <- newIORef prog1
    prog2 <- readIORef v
    let sol1 = solve prog1
        sol2 = solve prog2
        score1 = eval <$> sol1 <*> pure (_objective prog1)
        score2 = eval <$> sol2 <*> pure (_objective prog2)
    return $
      classify (isRight sol1) "feasible" $
      if score1 == score2
        then property True
        else property $
          MkResult (Just False) True
            ("\n" ++ show (score1,sol1) ++
             "\n" ++ show (score2,sol2))
            Nothing False Nothing mempty mempty mempty [show prog1]
```

The above program tests that `solve` gives the same value of the objective function for the same problem when evaluated two times in a row.

If you run this with, say, `./test --quickcheck-tests 20000`, you will sooner or later run into a counterexample, such as

```
limp: FAIL (3.50s)
  *** Failed! (after 4262 tests): 
  
  (Right 1.0,Right (Assignment (fromList [(1,0),(2,0),(3,0),(4,0),(5,0),(6,0),(7,0),(8,0),(9,1),(10,0)]) (fromList [])))
  (Right 2.0,Right (Assignment (fromList [(1,1),(2,0),(3,0),(4,0),(5,0),(6,0),(7,0),(8,0),(9,1),(10,0)]) (fromList [])))
  Program {_direction = Minimise, _objective = LR [(Left 1,1.0),(Left 2,1.0),(Left 3,1.0),(Left 4,1.0),(Left 5,1.0),(Left 6,1.0),(Left 7,1.0),(Left 8,1.0),(Left 9,1.0),(Left 10,1.0)] 0.0, _constraints = LZ [(1,1),(10,1)] 0 :== LZ [] 1 :&& (LZ [(4,1),(6,1),(7,1),(9,1),(10,1)] 0 :== LZ [] 1 :&& (LZ [(1,1),(3,1),(4,1),(6,1),(7,1)] 0 :== LZ [] 1 :&& (LZ [(4,1),(5,1),(6,1),(7,1),(9,1),(10,1)] 0 :== LZ [] 1 :&& (LZ [(3,1),(5,1),(9,1),(10,1)] 0 :== LZ [] 1 :&& CTrue)))), _bounds = [BoundZ (Just 0,1,Just 1),BoundZ (Just 0,2,Just 1),BoundZ (Just 0,3,Just 1),BoundZ (Just 0,4,Just 1),BoundZ (Just 0,5,Just 1),BoundZ (Just 0,6,Just 1),BoundZ (Just 0,7,Just 1),BoundZ (Just 0,8,Just 1),BoundZ (Just 0,9,Just 1),BoundZ (Just 0,10,Just 1)]}
  Use --quickcheck-replay=553233 to reproduce.

1 out of 1 tests failed (3.50s)
```

(Don't pay attention to `--quickcheck-replay`; this is non-deterministic.)

I doubt this is a problem in the Haskell package itself, but I thought I'd let you know.

If this is a bug in cbc, it might have been solved already ­— worth testing when #4 is fixed.

**Comment by feuerbach** [comment]
I found [this discussion](https://webcache.googleusercontent.com/search?q=cache:Q16BcZSfd9EJ:https://list.coin-or.org/pipermail/cbc/2016-February/001892.html) of non-determinism in cbc, but they talk only about a non-deterministic solution. A non-deterministic objective is a much bigger deal.

I haven't checked this particular example, but in my experiments the lower result is always wrong — so cbc occasionally generates an invalid solution, not just a suboptimal one.

**Comment by amosr** [comment]
This is scary. I'll have a look at this tomorrow

**Comment by feuerbach** [comment]
FWIW, I can still reproduce this when using a non-embedded cbc library (v2.9.8).

**Comment by amosr** [comment]
Yep, I can reproduce this with 2.9.9 and the embedded version.

Thanks for the excellent test case, by the way. I will add it to the repo. I added pretty-printing and checking the validity of the assignment. In the case below, the first assignment is invalid, while the second is valid.  This is crazy though: the first assignment has variable Z2 as -9e19 but the bounds for that indicate it should be 0 or 1.

What I'll do next is convert this program to the sparse matrix representation and then write a C++ program to do the same as your test case. Writing the C++ program directly should hopefully make it obvious if I'm using the CBC API incorrectly.

```
  (Right -1.8446744073709552e19,Right False,Right (Assignment (fromList [(1,-9223372036854775808),(2,-9223372036854775808),(3,1),(4,0),(5,0),(6,0),(7,0),(8,0),(9,0),(10,0)]) (fromList [])))
  (Right 1.0,Right True,Right (Assignment (fromList [(1,0),(2,0),(3,1),(4,0),(5,0),(6,0),(7,0),(8,0),(9,0),(10,0)]) (fromList [])))

  Minimize
  	1.0 Z1 + 1.0 Z2 + 1.0 Z3 + 1.0 Z4 + 1.0 Z5 + 1.0 Z6 + 1.0 Z7 + 1.0 Z8 + 1.0 Z9 + 1.0 Z10
  Subject to
  	-1.0 Z2 - 1.0 Z3 - 1.0 Z5 - 1.0 Z6 - 1.0 Z7 - 1.0 Z9 >= -1.0
  	-1.0 Z2 - 1.0 Z3 - 1.0 Z5 - 1.0 Z6 - 1.0 Z7 - 1.0 Z9 <= -1.0
  	-1.0 Z1 - 1.0 Z2 - 1.0 Z3 - 1.0 Z4 - 1.0 Z5 - 1.0 Z8 - 1.0 Z9 >= -1.0
  	-1.0 Z1 - 1.0 Z2 - 1.0 Z3 - 1.0 Z4 - 1.0 Z5 - 1.0 Z8 - 1.0 Z9 <= -1.0
  	-1.0 Z1 - 1.0 Z3 - 1.0 Z10 >= -1.0
  	-1.0 Z1 - 1.0 Z3 - 1.0 Z10 <= -1.0
  	-1.0 Z1 - 1.0 Z3 - 1.0 Z4 - 1.0 Z5 - 1.0 Z7 - 1.0 Z9 >= -1.0
  	-1.0 Z1 - 1.0 Z3 - 1.0 Z4 - 1.0 Z5 - 1.0 Z7 - 1.0 Z9 <= -1.0
  	-1.0 Z1 - 1.0 Z3 - 1.0 Z4 - 1.0 Z10 >= -1.0
  	-1.0 Z1 - 1.0 Z3 - 1.0 Z4 - 1.0 Z10 <= -1.0

  Bounds
  	0.0 <= Z1 <= 1.0
  	0.0 <= Z2 <= 1.0
  	0.0 <= Z3 <= 1.0
  	0.0 <= Z4 <= 1.0
  	0.0 <= Z5 <= 1.0
  	0.0 <= Z6 <= 1.0
  	0.0 <= Z7 <= 1.0
  	0.0 <= Z8 <= 1.0
  	0.0 <= Z9 <= 1.0
  	0.0 <= Z10 <= 1.0

  Generals
  Z1
  Z2
  Z3
  Z4
  Z5
  Z6
  Z7
  Z8
  Z9
  Z10
```

**Comment by amosr** [comment]
Good news, it's fixed! I wasn't touching the foreign pointer after copying the solution out, so the model was sometimes garbage collected in the middle of copying the solution, which freed the solution and corrupted the array.

This was quite hard to track down, but I'm moderately confident that there are not other issues like it, since this is the only place we need to copy arrays from C. The rest of the return types from C are just simple scalars. Perhaps it would have been simpler to allocate and copy the array in C in the first place.

**Comment by feuerbach** [comment]
Terrific, thanks!
